### ISSUE TITLE
Error submitting the spend bundles - spendable balance of 0

### ISSUE THREAD

**Issue by geraldneale** [Chia-Network/chia-nft-minting-tool#18]
Spendable balance of 0, but I obviously have more than zero in STANDARD_WALLET.

$ chianft submit-spend-bundles -f 137363085 -m 1000 output.pkl

ValueError: {'error': 'Transaction for 40000 is greater than spendable balance of 0. There may be other transactions pending or our minimum coin amount is too high.', 'success': False}

5)  * 137363085    chia-nft-minting-tool
Choose a wallet key [1-5] ('q' to quit, or Enter to use 137363085): 
Wallet height: 1979139
Sync status: Synced
Balances, fingerprint: 137363085

Chia Wallet:
   -Total Balance:         0.999999999999 txch (999999999999 mojo)
   -Pending Total Balance: 0.999999999999 txch (999999999999 mojo)
   -Spendable:             0.999999999999 txch (999999999999 mojo)
   -Type:                  STANDARD_WALLET
   -Wallet ID:             1

Profile 1:
   -Total Balance:         1.0  
   -Pending Total Balance: 1.0  
   -Spendable:             1.0  
   -Type:                  DECENTRALIZED_ID
   -DID ID:                did:chia:120sc4g2um5qnywhd580ljee90eaj93f9t9fr6ecz57sx2xqm6zpscuk48k
   -Wallet ID:             2

NFT Wallet:
   -Total Balance:         0.0  
   -Pending Total Balance: 0.0  
   -Spendable:             0.0  
   -Type:                  NFT
   -DID ID:                did:chia:120sc4g2um5qnywhd580ljee90eaj93f9t9fr6ecz57sx2xqm6zpscuk48k
   -Wallet ID:             3

NFT Wallet:
   -Total Balance:         0.0  
   -Pending Total Balance: 0.0  
   -Spendable:             0.0  
   -Type:                  NFT
   -Wallet ID:             5

**Comment by geoffwalmsley** [comment]
Hi Gerald,
Thanks for submitting your issue. In your testnet wallet, do you know if your balance is held in more than 1 coin?  When you go to submit the spend bundles it will use whichever coin was used to create the spends, and then needs a second coin from which it will create the fee transactions. Hope that helps, let me know if you have more trouble with this
