### ISSUE TITLE
Update to Chia 1.7 broke offer file creation

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-nft-minting-tool#29]
The recent version bump (https://github.com/Chia-Network/chia-nft-minting-tool/commit/ad477306122249f5c99bcf238cf54642efd22df3) has broken the offer file creation logic and results in the error:

![image](https://user-images.githubusercontent.com/48610606/225711882-ef1ba2e3-5e07-4f7f-8a81-b42ad52d9405.png)

I unfortunately have not had time to more thoroughly debug but have verified the issue on mac, windows, and linux all of which work on 1.6.2 so I imagine it is either offer file compression or rpc updates that are causing the issue.

**Comment by geoffwalmsley** [comment]
@BrandtH22 thanks for this. I haven't been able to reproduce this using the simulator - were you on test/main net?
Also could you just confirm that you're not minting the nfts to a target address, i.e. there is no `-t True` flag when you run `create-mint-spend-bundles`

**Comment by BrandtH22** [comment]
@geoffwalmsley upon further review I am not able to reproduce the issue and have identified an issue with the dev environment I was using that may have lead to the problem.

Thank you for looking into this and I am sorry for any confusion
