### ISSUE TITLE
Minted NFTs using -d True end up having an unassigned owner id

### ISSUE THREAD

**Issue by spacelabsnfts** [Chia-Network/chia-nft-minting-tool#6]
Hi have been playing with the tool, and I had a few observations/questions:

-Based on my testing, it looks like the only way to get it working with the chia client is using this branch (gw.bulk_mint_nfts) https://github.com/Chia-Network/chia-blockchain/blob/gw.bulk_mint_nfts/chia/rpc/wallet_rpc_api.py#L155
(which has the nft_mint_bulk wallet API). Is that correct? or is there another more up to date branch?

-I did a test using that branch, and it works, I minted several ones however the end up with an 'Unassigned' owner did (e.g. https://mintgarden.io/nfts/nft1g326nj04ajcaau3a2fwwuzf5mpwctr4r4xja7rdjt7psrzawwhxqxh24yf) . Even though I followed these steps:

>chia-nft-minting-tool % chianft create-mint-spend-bundles -w 3 -d True -a xch1p4xht2staxxqzspraqmkpfppqk0xaaq27ezdz3yjc0mzf0wgp3aqtd8qwg -r 600 metadata-1.csv output-1.pkl
>chia-nft-minting-tool % chianft submit-spend-bundles -m 1000000 output-1.pkl

(the -d True indicates use did)  and I put logs in the code and saw it that the spend bundle was using a coin associated with my did:chia:1gysj9pt28wzyf5fg97afysmyeaz5zuxnlsj8c0uqtr8t2tvskrpsyjdj9f

Thoughts?
cc: @geoffwalmsley

**Comment by cameroncooper** [comment]
Thanks for the report. 

1) When we release the beta later this week, it will be pointing to main and not an older branch

2) This minting tool uses a new technique to establish the minter. In the case of this tool all NFT coins are children of the DID coin. The marketplaces need to be updated to support this convention.

Hope this answers your questions.

**Comment by scotopic** [comment]
Hi,

Testing the minting to a DID and seeing the same issue where in the Chia client app the NFTs are not assigned to a DID.

The commands ran:

```
chia keys generate;

chia wallet did create -n bulk_mint_DI -m 0.0000001

chia wallet nft create -f 4096226521 -di did:chia:1cpv5x5hl4627p4n7thn3l3qu389u2yc06mf3h33m2sc4ycjmmawqq9tzxk -n "NFT Wallet for bulk minting"

python factory_metadata.py 3

chianft create-mint-spend-bundles -w 3 -a txch1dakenrvcg2sg90ullfv236euyt02457t52e5jv7m9gry9d255yaq24cjqw -r 300 -d True metadata.csv output.pkl

chianft submit-spend-bundles -m 100000 -o 100 output.pkl```

Screenshot 1 shows the output for the commands including a modified tool to show that it does indeed include the `did_coin_dict`. However, 
<img width="1547" alt="Screen Shot 2023-02-20 at 10 10 16 AM" src="https://user-images.githubusercontent.com/423735/220142827-2bec3155-ba3e-4d0e-b960-dd1501f64f06.png">

However, they are not showing up in the DID:
<img width="902" alt="Screen Shot 2023-02-20 at 10 11 58 AM" src="https://user-images.githubusercontent.com/423735/220143153-93c6f4c6-0c95-4d2f-a49d-91f3de833799.png">

A new non-DID wallet is created and the NFTs are unassigned:
<img width="784" alt="Screen Shot 2023-02-20 at 10 13 26 AM" src="https://user-images.githubusercontent.com/423735/220143473-564f9496-dbd2-401a-85b8-5e539f55685e.png">

Visible here as unassigned:
<img width="895" alt="Screen Shot 2023-02-20 at 10 15 16 AM" src="https://user-images.githubusercontent.com/423735/220143955-a0f31a34-d853-4040-8807-91aba19ff96e.png">

**Comment by scotopic** [comment]
Ignore above comment. Someone in the community pointed out that the Chia Wallet client doesn't set the DID after the mint. 

However, one can verify the NFTs were minted by the DID via:
`chia rpc wallet nft_get_nfts '{"wallet_id": 4}'`

if you used `-d True` you should see each NFT have `"minter_did": "0x6f55a0bd81edaeb513383e7fcecafa56874e7e596b682988fc8e7dde3a85f7e5",`

if you left the default or `-d False` (no DID) then you should see:
`"minter_did": null,`
